/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webrtc_audioprocessing_Apm_VAD_Likelihood */

#ifndef _Included_com_webrtc_audioprocessing_Apm_VAD_Likelihood
#define _Included_com_webrtc_audioprocessing_Apm_VAD_Likelihood
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
