/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webrtc_audioprocessing_Apm_AECM_RoutingMode */

#ifndef _Included_com_webrtc_audioprocessing_Apm_AECM_RoutingMode
#define _Included_com_webrtc_audioprocessing_Apm_AECM_RoutingMode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
