/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sinowave_ddp_Apm_NS_Level */

#ifndef _Included_com_webrtc_audioprocessing_Apm_NS_Level
#define _Included_com_webrtc_audioprocessing_Apm_NS_Level
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
