/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webrtc_audioprocessing_Apm_AGC_Mode */

#ifndef _Included_com_webrtc_audioprocessing_Apm_AGC_Mode
#define _Included_com_webrtc_audioprocessing_Apm_AGC_Mode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
