/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_webrtc_audioprocessing_Apm_AEC_SuppressionLevel */

#ifndef _Included_com_webrtc_audioprocessing_Apm_AEC_SuppressionLevel
#define _Included_com_webrtc_audioprocessing_Apm_AEC_SuppressionLevel
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
